commerce_payment.commerce_payment_gateway.plugin.iyzipay_onsite:
  type: commerce_payment_gateway_configuration
  mapping:
    api_key:
      type: string
      label: 'API key'
    secret_key:
      type: string
      label: 'Secret key'
    api_url:
      type: string
      label: 'API URL'
